### ISSUE TITLE
Bring it up to speed with recent changes in OJS master

### ISSUE THREAD

**Issue by NateWr** [NateWr/bootstrap3#31]
A number of recent and pending changes in OJS master require changes for this theme:

- [x] All user registration now goes through `userRegister.tpl` with some updates to the role selection process. https://github.com/pkp/pkp-lib/issues/1443
- [x] The tasks grid on the frontend was replaced with a simple notification status indicator. https://github.com/pkp/pkp-lib/issues/1461 Fixed in https://github.com/NateWr/bootstrap3/commit/9642b31f923d5f0e9caf431f21ea2f8c0dce2029
- [x] Many about the journal input fields were consolidated into a single one. https://github.com/pkp/pkp-lib/issues/1397
